import React from "react";
import { render } from "@testing-library/react";
import LaunchTile from "./index";
import { shallow } from "enzyme";

const allLaunch = [
  {
    flight_number: 10,
    mission_name: "CRS-2",
    mission_id: ["EE86F74"],
    launch_year: "2013",
    launch_date_unix: 1362165000,
    launch_date_utc: "2013-03-01T19:10:00.000Z",
    launch_date_local: "2013-03-01T15:10:00-04:00",
    is_tentative: false,
    tentative_max_precision: "hour",
    tbd: false,
    launch_window: 0,
    rocket: {
      rocket_id: "falcon9",
      rocket_name: "Falcon 9",
      rocket_type: "v1.0",
      first_stage: {
        cores: [
          {
            core_serial: "B0007",
            flight: 1,
            block: 1,
            gridfins: false,
            legs: false,
            reused: false,
            land_success: null,
            landing_intent: false,
            landing_type: null,
            landing_vehicle: null,
          },
        ],
      },
      second_stage: {
        block: 1,
        payloads: [
          {
            payload_id: "CRS-2",
            norad_id: [39115],
            cap_serial: "C104",
            reused: false,
            customers: ["NASA (CRS)"],
            nationality: "United States",
            manufacturer: "SpaceX",
            payload_type: "Dragon 1.0",
            payload_mass_kg: 677,
            payload_mass_lbs: 1492,
            orbit: "ISS",
            orbit_params: {
              reference_system: "geocentric",
              regime: "low-earth",
              longitude: null,
              semi_major_axis_km: 6640.79,
              eccentricity: 0.0089419,
              periapsis_km: 203.274,
              apoapsis_km: 322.036,
              inclination_deg: 51.6797,
              period_min: 89.761,
              lifespan_years: null,
              epoch: "2013-03-01T20:19:32.000Z",
              mean_motion: 16.04255447,
              raan: 281.5076,
              arg_of_pericenter: 50.5296,
              mean_anomaly: 127.2881,
            },
            mass_returned_kg: 1370,
            mass_returned_lbs: 3020,
            flight_time_sec: 2160000,
            cargo_manifest:
              "https://en.wikipedia.org/wiki/SpaceX_CRS-2#Payload",
          },
        ],
      },
      fairings: null,
    },
    ships: ["AMERICANISLANDER"],
    telemetry: { flight_club: null },
    launch_site: {
      site_id: "ccafs_slc_40",
      site_name: "CCAFS SLC 40",
      site_name_long:
        "Cape Canaveral Air Force Station Space Launch Complex 40",
    },
    launch_success: true,
    links: {
      mission_patch: "https://images2.imgbox.com/ef/39/FyZRYeOh_o.png",
      mission_patch_small: "https://images2.imgbox.com/1b/b6/Z4oktZeR_o.png",
      reddit_campaign: null,
      reddit_launch:
        "https://www.reddit.com/r/space/comments/19gm5f/live_coverage_spacex_crs2_launch_to_the_iss/c8nvah4",
      reddit_recovery: null,
      reddit_media: null,
      presskit:
        "https://www.nasa.gov/sites/default/files/files/Orb2_PRESS_KIT.pdf",
      article_link: "https://en.wikipedia.org/wiki/SpaceX_CRS-2",
      wikipedia: "https://en.wikipedia.org/wiki/SpaceX_CRS-2",
      video_link: "https://www.youtube.com/watch?v=ik0ElKl5kW4",
      youtube_id: "ik0ElKl5kW4",
      flickr_images: [],
    },
    details: "Last launch of the original Falcon 9 v1.0 launch vehicle",
    upcoming: false,
    static_fire_date_utc: "2013-02-25T18:30:00.000Z",
    static_fire_date_unix: 1361817000,
    timeline: {
      webcast_liftoff: 2393,
      go_for_prop_loading: -2280,
      rp1_loading: -2100,
      stage1_lox_loading: -2100,
      stage2_lox_loading: -960,
      engine_chill: -420,
      prelaunch_checks: -60,
      propellant_pressurization: -60,
      go_for_launch: -45,
      ignition: -3,
      liftoff: 0,
      maxq: 60,
      meco: 180,
      stage_sep: 180,
      second_stage_ignition: 180,
      "seco-1": 540,
      dragon_separation: 600,
      dragon_solar_deploy: 720,
      dragon_bay_door_deploy: 8400,
    },
    crew: null,
  },
  {
    flight_number: 11,
    mission_name: "CASSIOPE",
    mission_id: [],
    launch_year: "2013",
    launch_date_unix: 1380470400,
    launch_date_utc: "2013-09-29T16:00:00.000Z",
    launch_date_local: "2013-09-29T09:00:00-07:00",
    is_tentative: false,
    tentative_max_precision: "hour",
    tbd: false,
    launch_window: 0,
    rocket: {
      rocket_id: "falcon9",
      rocket_name: "Falcon 9",
      rocket_type: "v1.1",
      first_stage: {
        cores: [
          {
            core_serial: "B1003",
            flight: 1,
            block: 1,
            gridfins: false,
            legs: false,
            reused: false,
            land_success: false,
            landing_intent: true,
            landing_type: "Ocean",
            landing_vehicle: null,
          },
        ],
      },
      second_stage: {
        block: 1,
        payloads: [
          {
            payload_id: "CASSIOPE",
            norad_id: [39265],
            reused: false,
            customers: ["MDA"],
            nationality: "Canada",
            manufacturer: "MDA",
            payload_type: "Satellite",
            payload_mass_kg: 500,
            payload_mass_lbs: 1100,
            orbit: "PO",
            orbit_params: {
              reference_system: "geocentric",
              regime: "low-earth",
              longitude: null,
              semi_major_axis_km: 7170.241,
              eccentricity: 0.0659319,
              periapsis_km: 319.359,
              apoapsis_km: 1264.854,
              inclination_deg: 80.9684,
              period_min: 100.707,
              lifespan_years: 2,
              epoch: "2020-09-22T21:07:29.000Z",
              mean_motion: 14.29888141,
              raan: 212.5433,
              arg_of_pericenter: 18.1111,
              mean_anomaly: 344.2385,
            },
          },
        ],
      },
      fairings: {
        reused: false,
        recovery_attempt: false,
        recovered: false,
        ship: null,
      },
    },
    ships: ["AMERICANSPIRIT"],
    telemetry: { flight_club: null },
    launch_site: {
      site_id: "vafb_slc_4e",
      site_name: "VAFB SLC 4E",
      site_name_long: "Vandenberg Air Force Base Space Launch Complex 4E",
    },
    launch_success: true,
    links: {
      mission_patch: "https://images2.imgbox.com/89/bc/JcbcvuBI_o.png",
      mission_patch_small: "https://images2.imgbox.com/91/27/VhC1TTYN_o.png",
      reddit_campaign: null,
      reddit_launch: "http://www.reddit.com/r/spacex/comments/1ndlay",
      reddit_recovery: null,
      reddit_media: null,
      presskit:
        "https://spaceflightnow.com/falcon9/006/UpgradedF9DemoMission_PressKit.pdf",
      article_link:
        "http://www.parabolicarc.com/2013/09/29/falcon-9-launch-payloads-orbit-vandenberg/",
      wikipedia: "https://en.wikipedia.org/wiki/CASSIOPE",
      video_link: "https://www.youtube.com/watch?v=uFefasS6bhc",
      youtube_id: "uFefasS6bhc",
      flickr_images: [],
    },
    details:
      "Commercial mission and first Falcon 9 v1.1 flight, with improved 13-tonne to LEO capacity. Following second-stage separation from the first stage, an attempt was made to perform an ocean touchdown test of the discarded booster vehicle. The test provided good test data on the experiment-its primary objective-but as the booster neared the ocean, aerodynamic forces caused an uncontrollable roll. The center engine, depleted of fuel by centrifugal force, shut down resulting in the impact and destruction of the vehicle.",
    upcoming: false,
    static_fire_date_utc: "2013-09-19T00:00:00.000Z",
    static_fire_date_unix: 1379548800,
    timeline: {
      webcast_liftoff: 55,
      go_for_prop_loading: -2280,
      rp1_loading: -2100,
      stage1_lox_loading: -2100,
      stage2_lox_loading: -960,
      engine_chill: -420,
      prelaunch_checks: -60,
      propellant_pressurization: -60,
      go_for_launch: -45,
      ignition: -3,
      liftoff: 0,
      maxq: 78,
      meco: 163,
      stage_sep: 170,
      second_stage_ignition: 177,
      fairing_deploy: 217,
      "seco-1": 534,
      payload_deploy: 855,
    },
    crew: null,
  },
];

describe("launchTiles component - display the tiles", () => {
  it(
    ("should work with no props",
    () => {
      shallow(<LaunchTile />);
    })
  );
});
